### PR TITLE
Init Project

### PR DESCRIPTION
**Pull request by dailx-1056**
Create new rails project
"ready"
image

### CODE REVIEW

**Comment by dailx-1056** [comment]
Fix convention

**Comment by dailx-1056** [comment]
ready

**Comment by ngocvt-0484** [comment]
fix comment theo PR này em nhá
https://github.com/dungdnv-1036/sample_app/pull/1/files

**Comment by ngocvt-0484** [comment]
trong quá trình làm đọc coding convention em nhé
https://github.com/framgia/coding-standards/blob/master/vn/README.md

**Pull request closed without merging**
